"""Durable storage for dashboard-managed knowledge base entries.

Fixes a data-loss bug, not just a missing feature. Dashboard KB entries were
written to tenants/<id>/kb/dashboard/*.md inside the running container. The
ai-receptionist service has NO Railway volume (the only volume in the project
is postgres-volume, mounted on the Postgres service), and the Dockerfile is a
plain WORKDIR /app + COPY . . — so every deploy wiped them. The manager looked
like it worked: you could add an entry, the test box would retrieve it, and
then the next push silently deleted it.

Verified before migrating: all 11 non-default tenants reported 0 entries and
0 PDFs, so nothing needed rescuing.

Git-tracked docs (tenants/<id>/kb/*.md) are unaffected and stay on disk — they
ship with the image, survive deploys, and remain the tenant's onboarding
corpus. This table is only the dashboard-managed tier.

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-01
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None

# faq — a text/Q&A entry typed into the dashboard.
# pdf — text extracted from an uploaded PDF. The original file is archived to
#       R2 (source holds its key); this row holds the text retrieval reads.
_KINDS = ("faq", "pdf")


def upgrade() -> None:
    op.create_table(
        "kb_entries",
        # uuid4().hex, generated by the API exactly as it was for filenames, so
        # ids stay stable in shape and any URL already in a tenant's hands
        # keeps working.
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column(
            "tenant_id",
            sa.Text(),
            sa.ForeignKey("tenants.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.Text(), nullable=False, server_default="faq"),
        # Null for a plain note with no question, and for pdf rows.
        sa.Column("question", sa.Text(), nullable=True),
        # The body a tenant typed, or the text extracted from a PDF. This is
        # what gets embedded and searched.
        sa.Column("answer", sa.Text(), nullable=False),
        # Where the original lives: the R2 object key for pdf rows, null for faq.
        sa.Column("source", sa.Text(), nullable=True),
        # Display metadata with no query semantics — filename, size_bytes,
        # pages, truncated. JSONB rather than four columns because it is
        # kind-specific and read only to render the list; splitting it out
        # would add four always-null columns for every faq row.
        sa.Column("meta", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("kind IN ('faq','pdf')", name="ck_kb_entries_kind"),
    )
    # The list endpoint's exact access pattern: one tenant, newest first.
    op.create_index(
        "ix_kb_entries_tenant", "kb_entries", ["tenant_id", "updated_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_kb_entries_tenant", table_name="kb_entries")
    op.drop_table("kb_entries")
